In [1]:
import pandas as pd
import numpy as np

In [6]:
data = {'x1':[1,1,0,0],
       'x2':[0,1,0,1],
        'y':[0,0,1,1]}

df = pd.DataFrame(data)

In [7]:
df.head()

x1  x2  y
0   1   0  0
1   1   1  0
2   0   0  1
3   0   1  1

In [56]:
# create a Perceptron class
class Perceptron:
    """ Base perceptron class """
    def __init__(self, n_iter=100):
        self.n_iter = n_iter
        
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))
    
    def sigmoid_derivative(self, x):
        fx = self.sigmoid(x)
        return fx * (1 - fx)
    
    def fit(self, X, y):
        
        np.random.seed(42)
        
        self.weights = 2 * np.random.random((X.shape[1], 1)) - 1
        
        for i in range(self.n_iter):
            weighted_sum = np.dot(X, self.weights)
            activated_output = self.sigmoid(weighted_sum)
            
            # backprop
            error = y - activated_output
            adjustments = error * self.sigmoid_derivative(weighted_sum)
            self.weights = self.weights + np.dot(X.T, adjustments)
            
    def predict(self, X):
        weighted_sum = np.dot(X, self.weights)
        activated_output = self.sigmoid(weighted_sum)
        return activated_output

In [57]:
model = Perceptron()

In [107]:
X = df[['x1', 'x2']].values
y = df['y'].values

In [108]:
y.shape, X.shape

((4,), (4, 2))

In [64]:
X

array([[1, 0],
       [1, 1],
       [0, 0],
       [0, 1]])

In [66]:
y

array([0, 0, 1, 1])

In [78]:
y = np.array([df['y']]).T

In [83]:
y

array([[0],
       [0],
       [1],
       [1]])

In [84]:
y.shape

(4, 1)

In [79]:
model.fit(X, y)

In [80]:
model.weights

array([[-3.9091744 ],
       [ 1.82203941]])

In [87]:
model.predict(np.array([1,1]))

array([0.11035353])

In [88]:
weights = 2 * np.random.random((X.shape[1], 1)) -1

In [89]:
weighted_sum = np.dot(np.array([X]), weights)

In [92]:
y_pred = model.predict(np.array([[1,1], [1,0], [0,1], [0,0]]))

In [93]:
y_pred

array([[0.11035353],
       [0.01966268],
       [0.86081066],
       [0.5       ]])

In [94]:
[1 if x >= .5 else 0 for x in y_pred]

[0, 0, 1, 1]

In [95]:
fire on the nhooeiriweiu woiu'o'ii


SyntaxError: invalid syntax (<ipython-input-95-ab697744d6a9>, line 1)

In [113]:
# create a Perceptron class
class BasicNN:
    """ adding layer to perceptron """
    def __init__(self, inputs=8, hidden=4, output=1, n_iter=100):
        self.n_iter = n_iter
        self.inputs = inputs
        self.hidden_nodes = hidden
        self.output_nodes = output

        np.random.seed(42)
        
        self.weights1 = 2 * np.random.random((self.inputs, self.hidden_nodes)) - 1        
        self.weights2 = 2 * np.random.random((self.hidden_nodes, self.output_nodes)) - 1
        
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))
    
    def sigmoid_derivative(self, x):
        fx = self.sigmoid(x)
        return fx * (1 - fx)
    
    def fit(self, X, y):
        
        
        for i in range(self.n_iter):
            # feed forward
            
            # from input to hidden
            weighted_sum = np.dot(X, self.weights1)
            activated_hidden = self.sigmoid(weighted_sum)
            # from hidden to output
            weighted_sum_2 = np.dot(activated_hidden, self.weights2)
            activated_output = self.sigmoid(weighted_sum_2) 
            
            # backprop
            stage2_error = np.array([y]).T - activated_output
            stage2_adj = stage2_error * self.sigmoid_derivative(weighted_sum_2)
            
            stage1_error = np.dot(stage2_adj, self.weights2.T)
            stage1_adj = stage1_error * self.sigmoid_derivative(weighted_sum)
            self.weights1 = self.weights1 + np.dot(X.T, stage1_adj)
            self.weights2 = self.weights2 + np.dot(activated_hidden.T, stage2_adj)
            
    def predict(self, X):
        weighted_sum = np.dot(X, self.weights1)
        activated_hidden = self.sigmoid(weighted_sum)
        weighted_sum_2 = np.dot(activated_hidden, self.weights2)
        activated_output = self.sigmoid(weighted_sum_2)
        return activated_output

In [118]:
X

array([[1, 0],
       [1, 1],
       [0, 0],
       [0, 1]])

In [119]:
y

array([0, 0, 1, 1])

In [120]:
model2 = BasicNN(inputs=2, hidden=4, output=1)

In [121]:
model2.fit(X, y)

In [122]:
model2.weights1

array([[-1.71339427,  1.14196648,  2.91242604, -2.49036637],
       [-0.49297785, -0.64620078, -0.84138877,  0.56443991]])

In [123]:
model2.predict(np.array([1,1]))

array([0.11940144])

In [124]:
dir(model2)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'fit',
 'hidden_nodes',
 'inputs',
 'n_iter',
 'output_nodes',
 'predict',
 'sigmoid',
 'sigmoid_derivative',
 'weights1',
 'weights2']

In [179]:
y_pred2 = model2.predict(np.array([[1,1], [1,0], [0,1], [0,0]]))
y_pred2

ValueError: shapes (4,2) and (8,16) not aligned: 2 (dim 1) != 8 (dim 0)

In [181]:
X[0]

array([1, 0])

In [227]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')

In [228]:
from sklearn.preprocessing import MinMaxScaler

features = list(diabetes)[:-1]
target = 'Outcome'

In [229]:
diabetes

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [230]:
len(diabetes.iloc[0])

9

In [231]:
scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(diabetes[features])
y= diabetes[target]

In [232]:
X_scaled = X_scaled.copy().T
t = np.full((1,len(X_scaled[0])),1)
X_scaled = np.concatenate((X_scaled,t))
X_scaled = X_scaled.T
X_scaled.shape

(768, 9)

In [233]:
from sklearn.model_selection import train_test_split

In [234]:
y.shape

(768,)

In [235]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=.25, random_state=42)

In [238]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((576, 9), (192, 9), (576,), (192,))

In [241]:
np.array([[y_train]])
y_train.shape

(576,)

In [242]:
from sklearn.metrics import accuracy_score

model = Perceptron()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred = [1 if x >= .5 else 0 for x in y_pred]

accuracy = accuracy_score(y_pred, y_test)

Exception: Data must be 1-dimensional

In [244]:
from sklearn.metrics import accuracy_score

model2 = BasicNN(inputs=9, hidden=16, output=1, n_iter=1000)
model2.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred = [1 if x >= .5 else 0 for x in y_pred]

accuracy = accuracy_score(y_pred, y_test)

In [245]:
accuracy

0.359375

In [246]:
y_pred

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [142]:
data = dict({
    'x1': [0,0,1,0,1,1,0],
    'x2': [0,1,0,1,0,1,0],
    'x3': [1,1,1,0,0,1,0],
    'y': [0,1,1,1,1,0,0]
})

xor= pd.DataFrame.from_dict(data)


In [143]:
features = xor[['x1', 'x2', 'x3'
]]
target = xor['y']

In [144]:
model = BasicNN(inputs=3, hidden=4, output=1, n_iter=1000)
model.fit(features, target)
model.predict(features)

array([[0.01051637],
       [0.95046345],
       [0.95225567],
       [0.96010849],
       [0.95780932],
       [0.07282899],
       [0.03708818]])